apiVersion: ako.vmware.com/v1alpha1
kind: AKOConfig
metadata:
  finalizers:
  - ako.vmware.com/cleanup
  name: ako-config
  namespace: {{ .Release.Namespace }}
spec:
  imageRepository: {{ .Values.akoImage.repository }}
  imagePullPolicy: {{ .Values.akoImage.pullPolicy }}
  akoSettings:
    logLevel: {{ .Values.AKOSettings.logLevel }}
    fullSyncFrequency: {{ .Values.AKOSettings.fullSyncFrequency | quote }}
    apiServerPort: {{ .Values.AKOSettings.apiServerPort }}
    deleteConfig: {{ .Values.AKOSettings.deleteConfig }}
    disableStaticRouteSync: {{ .Values.AKOSettings.disableStaticRouteSync }}
    clusterName: {{ .Values.AKOSettings.clusterName }}
    cniPlugin: {{ .Values.AKOSettings.cniPlugin | quote }}
    namespaceSelector:
      labelKey: {{ .Values.AKOSettings.namespaceSelector.labelKey | quote }}
      labelValue: {{ .Values.AKOSettings.namespaceSelector.labelValue | quote }}

  networkSettings:
    subnetIP: {{ .Values.NetworkSettings.subnetIP | quote }}
    subnetPrefix: {{ .Values.NetworkSettings.subnetPrefix | quote }}
    networkName: {{ .Values.NetworkSettings.networkName | quote }}
    enableRHI: {{ .Values.NetworkSettings.enableRHI }}
{{- with .Values.NetworkSettings.nodeNetworkList }}
    nodeNetworkList:
      {{- toYaml . | nindent 4 }}
{{- end }}
  l7Settings:
    defaultIngController: {{ .Values.L7Settings.defaultIngController }}
    shardingScheme: {{ .Values.L7Settings.l7ShardingScheme | quote }}
    serviceType: {{ .Values.L7Settings.serviceType }}
    shardVSSize: {{ .Values.L7Settings.shardVSSize }}
    passthroughShardSize: {{ .Values.L7Settings.passthroughShardSize }}

  l4Settings:
    advancedL4: {{ .Values.L4Settings.advancedL4 }}
    defaultDomain: {{ .Values.L4Settings.defaultDomain | quote }}
    autoFQDN: {{ .Values.L4Settings.autoFQDN | quote }}

  controllerSettings:
    serviceEngineGroupName: {{ .Values.ControllerSettings.serviceEngineGroupName | quote }}
    controllerVersion: {{ .Values.ControllerSettings.controllerVersion | quote }}
    cloudName: {{ .Values.ControllerSettings.cloudName | quote }}
    controllerIP: {{ .Values.ControllerSettings.controllerHost | quote }}
    tenantsPerCluster: {{ .Values.ControllerSettings.tenantsPerCluster }}
    tenantName: {{ .Values.ControllerSettings.tenantName | quote }}

  nodePortSelector: # only applicable if servicetype is nodePort
    key: {{ .Values.nodePortSelector.key | quote }}
    value: {{ .Values.nodePortSelector.value | quote }}

  resources:
    limits:
      cpu: {{ .Values.resources.limits.cpu }}
      memory: {{ .Values.resources.limits.memory }}
    requests:
      cpu: {{ .Values.resources.requests.cpu }}
      memory: {{ .Values.resources.requests.memory }}

  rbac:
    pspEnable: {{ .Values.rbac.pspEnable }}

{{ if .Values.persistentVolumeClaim }}
  persistentVolumeClaim: .Values.persistentVolumeClaim
{{ end }}

  mountPath: {{ .Values.mountPath }}
  logFile: {{ .Values.logFile }}
