apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ako-operator-manager-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["ako.vmware.com"]
  resources: ["akoconfigs", "akoconfigs/status", "akoconfigs/finalizers"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "statefulsets/status"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings", "clusterroles"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses", "ingresses/status"]
  verbs: ["get","watch","list","patch", "update"]
- apiGroups: [""]
  resources: ["services/status"]
  verbs: ["get","watch","list","patch", "update"]
- apiGroups: ["crd.projectcalico.org"]
  resources: ["blockaffinities"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["network.openshift.io"]
  resources: ["hostsubnets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes", "routes/status"]
  verbs: ["get", "watch", "list", "patch", "update"]
- apiGroups: ["ako.vmware.com"]
  resources: ["hostrules", "hostrules/status", "httprules", "httprules/status"]
  verbs: ["get","watch","list","patch", "update"]
- apiGroups: ["networking.x-k8s.io"]
  resources: ["gateways", "gateways/status", "gatewayclasses", "gatewayclasses/status"]
  verbs: ["get","watch","list","patch", "update"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ['get', 'watch', 'list']
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
