---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ako-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ako-operator-manager-role
subjects:
- kind: ServiceAccount
  name: ako-operator-sa
  namespace: avi-system
