{{- if .Values.AKOSettings.primaryInstance }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ako-cr
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ['get','watch','list']
  - apiGroups: ["apps"]
    resources: ["statefulsets","statefulsets/status"]
    verbs: ["get","watch","list","patch","update"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses","ingresses/status"]
    verbs: ["get","watch","list","patch","update"]
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass" }}
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get","watch","list"]
{{- end}}
  - apiGroups: [""]
    resources: ["services","services/status"]
    verbs: ["get","watch","list","patch","update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","watch","list","patch","update", "create"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","watch","list","patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch","update"]
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["blockaffinities"]
    verbs: ["get","watch","list"]
  - apiGroups: ["network.openshift.io"]
    resources: ["hostsubnets"]
    verbs: ["get","watch","list"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes","routes/status"]
    verbs: ["get","watch","list","patch","update"]
  - apiGroups: ["ako.vmware.com"]
    resources: ["hostrules","hostrules/status","httprules","httprules/status","aviinfrasettings","aviinfrasettings/status", "l4rules", "l4rules/status", "ssorules", "ssorules/status", "l7rules", "l7rules/status"]
    verbs: ["get","watch","list","patch","update"]
  - apiGroups: ["networking.x-k8s.io"]
    resources: ["gateways","gateways/status","gatewayclasses","gatewayclasses/status"]
    verbs: ["get","watch","list","patch","update"]
  - apiGroups: ["ako.vmware.com"]
    resources: ["multiclusteringresses","serviceimports"]
    verbs: ["get","watch","list","patch"]
  - apiGroups: ["ako.vmware.com"]
    resources: ["multiclusteringresses/status","serviceimports/status"]
    verbs: ["get","patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "update"]
  - apiGroups: ["cilium.io"]
    resources: ["ciliumnodes"]
    verbs: ["get","watch","list"]
{{- if eq .Values.featureGates.GatewayAPI true }}
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses", "gatewayclasses/status","gateways","gateways/status","httproutes","httproutes/status"]
    verbs: ["get","watch","list","patch","update"]
{{- end }}
{{- if eq .Values.featureGates.EnableEndpointSlice true }}
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get","watch","list"]
{{- end }} 
{{- if .Values.rbac.pspEnable }}
  - apiGroups: ["policy", "extensions"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["{{ template "ako.name" . }}"]
{{- end }}
{{- end }}
