apiVersion: v1
kind: ConfigMap
metadata:
  name: avi-k8s-config
  namespace: {{ .Release.Namespace }}
data:
  primaryInstance: {{ .Values.AKOSettings.primaryInstance | quote }}
  controllerIP: {{ .Values.ControllerSettings.controllerHost | quote }}
  controllerVersion: {{ .Values.ControllerSettings.controllerVersion | quote }}
  cniPlugin: {{ .Values.AKOSettings.cniPlugin | quote }}
  shardVSSize: {{ .Values.L7Settings.shardVSSize | quote }}
  passthroughShardSize: {{ .Values.L7Settings.passthroughShardSize | quote }}
  fullSyncFrequency: {{ .Values.AKOSettings.fullSyncFrequency | quote }}
  cloudName: {{ .Values.ControllerSettings.cloudName | quote }}
  clusterName: {{ .Values.AKOSettings.clusterName | quote }}
  servicesAPI: {{ .Values.AKOSettings.servicesAPI | quote }}
  enableEVH: {{ .Values.AKOSettings.enableEVH | quote }}
  layer7Only: {{ .Values.AKOSettings.layer7Only | quote }}
  vipPerNamespace: {{ .Values.AKOSettings.vipPerNamespace | quote }}
  tenantName: {{ .Values.ControllerSettings.tenantName | quote }}
  defaultDomain: {{ .Values.L4Settings.defaultDomain | quote }}
  disableStaticRouteSync: {{ .Values.AKOSettings.disableStaticRouteSync | quote }}
  defaultIngController: {{ .Values.L7Settings.defaultIngController | quote }}
  noPGForSNI: {{ .Values.L7Settings.noPGForSNI | quote }}
  enableRHI: {{ .Values.NetworkSettings.enableRHI | quote }}
  nsxtT1LR: {{ .Values.NetworkSettings.nsxtT1LR | quote }}
  enableEvents: {{ .Values.AKOSettings.enableEvents | quote }}
  logLevel: {{ .Values.AKOSettings.logLevel | quote }}
  deleteConfig: {{ .Values.AKOSettings.deleteConfig | quote }}
  autoFQDN: {{ .Values.L4Settings.autoFQDN | quote }}
  nsSyncLabelKey: {{ .Values.AKOSettings.namespaceSelector.labelKey | quote }}
  nsSyncLabelValue: {{ .Values.AKOSettings.namespaceSelector.labelValue | quote }}
  serviceType:  {{ .Values.L7Settings.serviceType | quote }}
  {{ if eq .Values.L7Settings.serviceType "NodePort" }}
  nodeKey: {{ .Values.nodePortSelector.key | quote }}
  nodeValue: {{ .Values.nodePortSelector.value | quote }}
  {{ end }}
  serviceEngineGroupName:  {{ .Values.ControllerSettings.serviceEngineGroupName | quote }}
  bgpPeerLabels: |-
    {{ .Values.NetworkSettings.bgpPeerLabels | mustToJson }}
  nodeNetworkList: |-
    {{ .Values.NetworkSettings.nodeNetworkList | mustToJson }}
  vipNetworkList: |-
    {{ .Values.NetworkSettings.vipNetworkList | mustToJson }}
  apiServerPort: {{ default "8080" .Values.AKOSettings.apiServerPort | quote }}
  enableMCI: {{ .Values.L7Settings.enableMCI | quote }}
  blockedNamespaceList: |-
    {{ .Values.AKOSettings.blockedNamespaceList | mustToJson }}
  ipFamily: {{ .Values.AKOSettings.ipFamily | quote }}
  istioEnabled: {{ .Values.AKOSettings.istioEnabled | quote }}
