apiVersion: v1
kind: ConfigMap
metadata:
  name: avi-k8s-config
  namespace: {{ .Release.Namespace }}
data:
  controllerIP: {{ .Values.configs.controllerIP | quote }}
  controllerVersion: {{ .Values.configs.controllerVersion | quote }}
  cniPlugin: {{ .Values.configs.cniPlugin | quote }}
  shardVSSize: {{ .Values.configs.shardVSSize | quote }}
  shardVSPrefix: {{ .Values.configs.shardVSPrefix | quote }}
  fullSyncFrequency: {{ .Values.configs.fullSyncFrequency | quote }}
  cloudName: {{ .Values.configs.cloudName | quote }}
  vrfRefName: {{ .Values.configs.vrfRefName | quote }}
  disableStaticRouteSync: {{ .Values.configs.disableStaticRouteSync | quote }}
  ingressApi: {{ .Values.configs.ingressApi | quote }}
  defaultIngController: {{ .Values.configs.defaultIngController | quote }}
  subnetIP: {{ .Values.configs.subnetIP | quote }}
  CIDR: {{ .Values.configs.CIDR | quote }}
  NetworkName: {{ .Values.configs.NetworkName | quote }}
  L7ShardingScheme: {{ .Values.configs.L7ShardingScheme | quote }}
