apiVersion: v1
kind: ConfigMap
metadata:
  name: avi-k8s-config
  namespace: {{ .Release.Namespace }}
data:
  controllerIP: {{ .Values.configs.controllerIP | quote }}
  controllerVersion: {{ .Values.configs.controllerVersion | quote }}
  cniPlugin: {{ .Values.configs.cniPlugin | quote }}
  shardVSSize: {{ .Values.configs.shardVSSize | quote }}
  passthroughShardSize: {{ .Values.configs.passthroughShardSize | quote }}
  fullSyncFrequency: {{ .Values.configs.fullSyncFrequency | quote }}
  cloudName: {{ .Values.configs.cloudName | quote }}
  clusterName: {{ .Values.configs.clusterName | quote }}
  defaultDomain: {{ .Values.configs.defaultDomain | quote }}
  disableStaticRouteSync: {{ .Values.configs.disableStaticRouteSync | quote }}
  ingressApi: {{ .Values.configs.ingressApi | quote }}
  defaultIngController: {{ .Values.configs.defaultIngController | quote }}
  subnetIP: {{ .Values.configs.subnetIP | quote }}
  subnetPrefix: {{ .Values.configs.subnetPrefix | quote }}
  networkName: {{ .Values.configs.networkName | quote }}
  l7ShardingScheme: {{ .Values.configs.l7ShardingScheme | quote }}
  logLevel: {{ .Values.configs.logLevel | quote }}
  deleteConfig: {{ .Values.configs.deleteConfig | quote }}
  {{ if .Values.configs.syncNamespace  }}
  syncNamespace: {{ .Values.configs.syncNamespace | quote }}
  {{ end }}
  serviceType:  {{ .Values.configs.serviceType | quote }}
  {{ if eq .Values.configs.serviceType "NodePort" }}
  nodeKey: {{ .Values.nodePortSelector.key | quote }}
  nodeValue: {{ .Values.nodePortSelector.value | quote }}
  {{ end }}
  
