apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nsxalbinfrasettings.ako.vmware.com
spec:
  conversion:
    strategy: None
  group: ako.vmware.com
  names:
    kind: NsxAlbInfraSetting
    listKind: NsxAlbInfraSettingList
    plural: nsxalbinfrasettings
    singular: nsxalbinfrasetting
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NSX ALB Setting is used to select specific Avi controller infra attributes.
        properties:
          spec:
            properties:
              network:
                properties:
                  name:
                    type: string
                  rhi:
                    type: boolean
                type: object
                required:
                - name
              seGroup:
                properties:
                  name:
                    type: string
                type: object
                required:
                - name
              l7Settings:
                properties:
                  shardSize:
                    enum:
                    - SMALL
                    - MEDIUM
                    - LARGE
                    - DEDICATED
                    type: string
                type: object
                required:
                - shardSize
            type: object
          status:
            properties:
              error:
                type: string
              status:
                type: string
            type: object
        type: object
    additionalPrinterColumns:
    - description: status of the nas object
      jsonPath: .status.status
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    served: true
    storage: true
    subresources:
      status: {}
