name: Go-CI

on:
  # Triggers the workflow on pull request events for the master  and release-* branches
  pull_request:
    branches:
      - master
      - release-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  golangci-lint:
    name: Golangci-lint
    strategy:
      matrix:
        platform: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.23.8
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.8'
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Run golangci-lint
      run: make golangci
